### ISSUE TITLE
condo should emit a better error message when executed from a path that is not initialized with git

### ISSUE THREAD

**Issue by dmccaffery** [automotiveMastermind/condo#121]
@agnauck reported this

When running condo in a folder that does not have git initialized, Condo will throw on the `RecommendVersion` Task.

Instead of throwing the exception condo should skip this task or fail with a pretty message

**Comment by dmccaffery** [comment]
@sjk07: is this solved by the warning in your latest PR for unity?

**Comment by sjk07** [comment]
@dmccaffery no, I removed it because it didn't fix this issue. wanted to create another PR specifically for this
